### ISSUE TITLE
Past Broadcasts Cannot be Downloaded

### ISSUE THREAD

**Issue by Sav0ia** [fkyn/younow-dl#1]
Thanks for the script :) the past broadcasts are listed but cannot be downloaded- they return this...

`error: cannot get video data TypeError: Cannot read property 'errorMsg' of undefined
    at /usr/local/lib/node_modules/younow-dl/lib/user.js:190:41
    at tryCatcher (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/promise.js:636:18)
    at PropertiesPromiseArray.PromiseArray._resolve (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PropertiesPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/props.js:78:14)
    at Promise._settlePromise (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/younow-dl/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
`

However a recent broadcast from yesterday can be downloaded...

Thanks!

**Comment by ceberous** [comment]
same error
